---
# Run the playbook setup_users_localhost.yml before this one
#
# ansible-playbook ../../setup_users_localhost.yml -K
#
# TODO: Integrate this as a task
#
# - name: Setup users localhost
#   import_tasks: setup_users_localhost.yml

- name: Setup users remote
  import_tasks: setup_users_remote.yml
  