---
# tasks file for datadisk-n01465744
- name: Create partition 1
  community.general.parted:
    device: "{{ partition_1.device }}"
    number: "{{ partition_1.number }}"
    name: "{{ partition_1.name }}"
    label: "{{ partition_1.label }}"
    state: "{{ partition_1.state }}"
    part_end: "{{ partition_1.part_end }}"

- name: Create xfs filesystem on partition 1
  community.general.filesystem:
    device: "{{ partition_1.device }}{{ partition_1.number }}"
    fstype: "{{ partition_1.fs_type }}"

- name: Mount xfs partition
  ansible.posix.mount:
    path: "{{ partition_1.mount }}"
    src: "{{ partition_1.device }}{{ partition_1.number }}"
    fstype: "{{ partition_1.fs_type }}"
    state: "{{ partition_1.mount_state }}"

- name: Create partition 2
  community.general.parted:
    device: "{{ partition_2.device }}"
    number: "{{ partition_2.number }}"
    name: "{{ partition_2.name }}"
    label: "{{ partition_2.label }}"
    state: "{{ partition_2.state }}"
    part_start: "{{ partition_2.part_start }}"
    part_end: "{{ partition_2.part_end }}"

- name: Create ext4 filesystem on partition 2
  community.general.filesystem:
    device: "{{ partition_2.device }}{{ partition_2.number }}"
    fstype: "{{ partition_2.fs_type }}"

- name: Mount ext4 partition
  ansible.posix.mount:
    path: "{{ partition_2.mount }}"
    src: "{{ partition_2.device }}{{ partition_2.number }}"
    fstype: "{{ partition_2.fs_type }}"
    state: "{{ partition_2.mount_state }}"
...
